### ISSUE TITLE
Asp .Net Core 3.0: InstancePerLifetimeScope resolved from MultitenantContainer is not disposed after http request ends.

### ISSUE THREAD

**Issue by wmaryszczak** [autofac/Autofac.AspNetCore.Multitenant#15]
I prepared sandbox application which reproduces that issue (test2 route)

## requirements

netcore 3.0

## how to run

```
git clone git@github.com:wmaryszczak/autofac_test.git
cd autofac_test
dotnet run
```

## test1

It throws `DependencyResolutionException` while resolving controller contructor's deps.

`action:`
GET http://localhost:5000/test1?t=test

`current behaviour:`
unable to resolve dependencies regsistered via MultitenantContainer

`expected behaviour:`
all dependencies are resolved from root container because of `services.AddControllersAsServices()` inside Starup.cs

## test2

Autofac does not respect declared lifecycle on registration phase

`action:`
GET http://localhost:5000/test2?t=test

`current behaviour:`
dependencies are resolved explicitly from MultitenantContainer, but its lifetime is not respected. `InstancePerLifetimeScope` dependencies acts as singleton.

`expected behaviour:`
`InstancePerLifetimeScope` is respected, so Dispose must be called after http request finish for deps. resistreder in MultitenantContainer (class: `DepPerTenant`) and in root container (class: `DepScoped`)

`observation:`

traces from Dispose method is printed on console after application's shut down

```
7140620 autofac_test.Deps.DepScoped.Dispose
62810779 autofac_test.Deps.DepSingleton.Dispose
```

## test3

Everything work fine, only because I do not resolve any tenant register dependency

`action:`
GET http://localhost:5000/test3?t=test

## hint

Each dependency print its instance hash code and lifecycle (ctor, work, dispose) on the console output.

**Comment by alsami** [comment]
Thanks for reporting this! Will look into it.

**Comment by alsami** [comment]
@wmaryszczak I investigated the problems you described.

#### Test-Case 1:

You are injecting a registration of `DepPerTenant` within `TestController` without passing in a `tenant-id`. Since you haven't registered a default implementation, you receive an exception because there simply is no registration. Simplest solution would be to inject this class last and let it default to `null`

```csharp
public Test1Controller(
IServiceProvider services,
DepSingleton singleton,
DepScoped scoped, ILogger<Test1Controller> logger, DepPerTenant tenant1 = null)
{
    this.tenant1 = tenant1;
    this.singleton = singleton;
    this.scoped = scoped;
    this.logger = logger;
    this.services = services;
}
```

You could also have a default implementation as can be seen [here](https://github.com/autofac/Autofac.AspNetCore.Multitenant/blob/develop/samples/Sandbox.Shared/ContainerSetup.cs#L9) in the `Sandbox-Sample`. This very much depends on the use-case though so you decide.

#### Test-Case 2:

Your `TenantIdentificationStrategy` does not work. You are doing the following

```csharp
public bool TryIdentifyTenant(out object tenantId)
{
    tenantId = null;
    if(this.httpContextAccessor.HttpContext?.Request?.Query?.TryGetValue("t", out var t) == true)
    {
        tenantId = t;
        return true;
    }
    return tenantId != null;
}
```

The return value of that `TryGetValue` returns a collection of string-values, since a query-parameter could be passed in as a collection as well.

Easiest fix would be to this 

```csharp
if(this.httpContextAccessor.HttpContext?.Request?.Query?.TryGetValue("t", out var t) == true)
{
    tenantId = t[0]; // use the indexer to get the first value which equals test when using the url provided by you http://localhost:5000/test2?t=test
    return true;
}
```

Within the `Test2Controller` you don't need to manually resolve the dependencies. Change the constructor to this

```csharp
public DependencyResolutionException(IServiceProvider services, DepScoped scoped, DepSingleton singleton, DepPerTenant tenant1)
{
    this.services = services;
    this.scoped = scoped;
    this.singleton = singleton;
    this.tenant1 = tenant1;
}
```

Now if you set a break-point in the constructor and in dispose-method you will see, that the lifetime-scope is respected and the class is created and disposed on each request exactly like it should be.

I hope this helps. Keep in mind that you can always clone this repository and run the samples to figure out how it works. Hope that helps!

**Comment by wmaryszczak** [comment]
@alsami  Thank you for the explanation and appologise for a late response. My sandbox was rather naive but the problem exists (test case 2) in my production application despite proper implementation of ITenantIdentificationStrategy. 
I have a use case to resolve dependencies directly from MultitenantContainer using GetTenantScope method. Here is the explanation.

I have an application which is a hybrid of http (asp net core framework) stack, where ITenantIdentificationStrategy based on IHttpContextAccessor determines current tenant; and rabbitmq event handler where incomming messages are also per tenant.
There are common per tenant dependencies for both asp and rabbitmq requests. 
In the rabbitmq part I don't have IHttpContextAccessor so I need to read tenant from incomming message the resolve dependency using GetTenantScope method.

I can only have one MultitenantContainer, so only one ITenantIdentificationStrategy, but I need two ways of resolving current tenant.


The documentation allows that, so still it should keep the object lifecycle as requested during dependency registration phase:
https://autofaccn.readthedocs.io/en/latest/advanced/multitenant.html#resolve-tenant-specific-dependencies

```
If you need to specifically access a tenant’s lifetime scope or the application container, the MultitenantContainer provides:

ApplicationContainer: Gets the application container.
GetCurrentTenantScope: Identifies the current tenant and returns their specific lifetime scope.
GetTenantScope: Allows you to provide a specific tenant ID for which you want the lifetime scope.
```

**Comment by alsami** [comment]
@wmaryszczak can you provide a small and clear example showing what is not working and describing within the code how it should be working? If it requires a rabbit-mq connection that would be fine as well.

I will look into then.

**Comment by wmaryszczak** [comment]
@alsami I looked deeper into the dependency injection graph of my application. It seems that I have to redesign my dependencies.  On sandbox level everything works as expected. 
Best regards
WM
