### ISSUE TITLE
RegisterBuildCallback callback registered while configuring tenant is not called when tenant container is built

### ISSUE THREAD

**Issue by robbmaclean** [autofac/Autofac.AspNetCore.Multitenant#19]
Hi, hopefully I'm writing this in the correct project-

I expected that I could use `RegisterBuildCallback` on the `ContainerBuilder` that is passed into the `ConfigureTenant` to access the tenant container once it is built, but this doesn't seem to be working for me.  Does this seem fishy?

I'm on `Autofac.AspNetCore.Multitenant` version `2.0.1`.

Here's a repo that demostrates this behavior (the point is that the callback registered on line 56 of `Startup.cs` does not execute):
https://bitbucket.org/robbmaclean/autofac-issue-maybe/src/master/

In a nutshell, here's the relevant part of `Startup.cs`:
```csharp
        public void ConfigureContainer(ContainerBuilder builder)
        {
            // This callback gets executed
            builder.RegisterBuildCallback(c =>
            {
                var logger = c.Resolve<ILogger<Startup>>();
                logger.LogInformation("Root container built");
            });
        }

        public static MultitenantContainer ConfigureMultitenantContainer(IContainer container)
        {
            var strategy = container.Resolve<ITenantIdentificationStrategy>();
            var multitenantContainer = new MultitenantContainer(strategy, container);
            multitenantContainer.ConfigureTenant(1, builder =>
            {
                builder.RegisterInstance(new Thingy("Tenant 1")).SingleInstance();
                // This callback does not get executed
                builder.RegisterBuildCallback(c =>
                {
                    var logger = c.Resolve<ILogger<Startup>>();
                    logger.LogInformation("Tenant 1 container built");
                });
            });
            return multitenantContainer;
        }
```

Thanks!

**Comment by tillig** [comment]
For Autofac 4.x this is the expected behavior. A build callback happens when a _container_ is _built_. When you are configuring a tenant, each tenant is only getting a _lifetime scope_, not a full container. There's no additional container actually being built.

There is [a pull request we accepted](https://github.com/autofac/Autofac/pull/1054) in core Autofac that adds the ability to register callbacks in lifetime scopes and have those execute on creation of a scope. This will be released in Autofac 5. When that's out, the behavior you're looking to achieve (a build callback registered in a tenant lifetime scope) will work. We are trying to get Autofac 5 out soon, but there is no guaranteed timeline.

**Comment by robbmaclean** [comment]
Great! Thank you for the response.
