### ISSUE TITLE
References to objects not cleaned up

### ISSUE THREAD

**Issue by cpkuo** [autofac/Autofac.AspNetCore.Multitenant#39]
I have an issue where the MultiTenant container is not releasing objects from memory. The way I have it set up is for 1 particular tenant, all it’s services are registered in ConfigureServices and not in the ConfigureMultitenantContainer method. Then in the TenantIdentificationStrategy, if its resolving for this particular tenant, I return false so that resolution happens in the parent container (I’m thinking this is the aspnetcore request child-generated container?). Then when resolving tenant services, its standardized to use the MultitenantContainer provider. My question is would this configuration lead to the strong references to these objects?

**Comment by tillig** [comment]
Yes, you need to resolve all tenants from their lifetime scope. Think of it like a hierarchy.

- root/container
  - tenant 1 scope
    - request for tenant 1 scope
  - tenant 2 scope
    - request for tenant 2 scope

If something is resolved in the request scope, when the request is done, it disposes of the scope and, in turn, disposes of items in the scope.

If you bypass all that and go straight to the container, you're also bypassing the disposal of the request scope and, yeah, things are going to live for the entire app lifetime.

That's why [in the docs](https://autofac.readthedocs.io/en/latest/lifetime/index.html) we specifically state:

> **It is important to always resolve services from a lifetime scope and not the root container.** Due to the disposal tracking nature of lifetime scopes, if you resolve a lot of disposable components from the container (the “root lifetime scope”), you may inadvertently cause yourself a memory leak. The root container will hold references to those disposable components for as long as it lives (usually the lifetime of the application) so it can dispose of them. [You can change disposal behavior if you choose](https://autofac.readthedocs.io/en/latest/lifetime/disposal.html), but it’s a good practice to only resolve from a scope. If Autofac detects usage of a singleton or shared component, it will automatically place it in the appropriate tracking scope.
