### ISSUE TITLE
Potential issue accessing HttpContext from Tenant ID Strategy

### ISSUE THREAD

**Issue by jontycg** [autofac/Autofac.AspNetCore.Multitenant#40]
## Describe the Bug

Hi there, 
I seem to be encountering what could be an issue with accessing HttpContext in the Tenant ID strategy (although would be happy to be advised if I am misusing).

It seems like whenever I access http context in the tenant ID strategy, the types are not injected correctly and instead the default types are.

Changing only the strategy to a different one (one that randomly assigns a tenant ID) seems to inject the types as expected so I'm lead to believe I'm either accessing HttpContext incorrectly or there is an issue with the library.

## Steps to Reproduce
I have set up a small repo demonstrating the issue here: https://github.com/jontycg/AutoFacMultiTenantHttpContextDemo

I have set up an interface `IGreeter.cs` which just allows for returning a string greeting. I have three classes that implement it, `DefaultGreeter`, `NumberOneGreeter` and `NumberTwoGreeter`.

You can see in `startup.cs` I have
```
 public void ConfigureContainer(ContainerBuilder builder)
  {
      builder.RegisterType<DefaultGreeter>().As<IGreeter>();
  }
  
  public static MultitenantContainer ConfigureMultitenantContainer(IContainer container)
  {
      // If the strategy is changed to RngTenantIdentificationStrategy it will work (but tenants will be assigned
      // randomly)
      var strategy = new HeaderTenantIdentificationStrategy();
      var mtc = new MultitenantContainer(strategy, container);
      mtc.ConfigureTenant("one", cb => cb.RegisterType<NumberOneGreeter>().As<IGreeter>());
      mtc.ConfigureTenant("two", cb => cb.RegisterType<NumberTwoGreeter>().As<IGreeter>());
      return mtc;
  }
```

Where I register the type `DefaultGreeter` as the default for that interface and then assign different types for tenants with IDs "one" and "two".

When using the current Tenant ID strategy, it will always return the default greeting, even if I pass in a tenant that correctly matches the IDs via a header (as defined in the strategy).

However, if you change the strategy to use `RngTenantIdentificationStrategy` which just randomly assigns a tenant ID and doesn't interact with HttpContext, it will now randomly alternate between the `NumberOneGreeter` and `NumberTwoGreeter` correctly, implying that the rest of the wiring seems correct.

It seems like there is an issue with injecting the correct types when Http Context is involved.

Note: I've also placed a breakpoint in the `HeaderTenantIdentificationStrategy` class and can see when I send a request it is returning the correct tenant ID, it just doesn't seem to change anything.

## Expected Behavior

When using HttpContext in the tenant ID strategy, will correctly inject tenant specific types.

## Dependency Versions

Autofac.AspNetCore.Multitenant: 5.0.0
Target Framework: netcoreapp3.1

---
Appreciate everything you do and all of your contributions, apologies in advance if I'm using it incorrectly :)

**Comment by tillig** [comment]
It's going to be a while before I can personally step through an example to debug it. I know we have a working .NET Core 3.1 example in the `examples` folder in this repo. The tenant ID strategy there uses the query string from `HttpContext` so I know it's possible. I haven't been able to compare your example to the one here, but that's where I'd start if I were you.

**Comment by alsami** [comment]
You should not create an instance of `IHttpContextAccessor` yourself.

Please follow the [sandbox sample](https://github.com/autofac/Autofac.AspNetCore.Multitenant/blob/develop/samples/Sandbox.Shared/QueryStringTenantIdentificationStrategy.cs#L15). That way it's safe to do what you are trying and should work as expected.

**Comment by jontycg** [comment]
That's a fair point, I just updated my demo repo to do it using that method and still experiencing the same issue. I can still place a breakpoint and see the tenant ID being picked up, but just doesn't seem to help with the tenant specific registrations. 

You can see my commit here in case I missed anything: 
https://github.com/jontycg/AutoFacMultiTenantHttpContextDemo/commit/9e60139b4d4aa34d2e376db073b3df007ad40556

**Comment by tillig** [comment]
As an experiment, can you try changing from using headers to using the query string?

There's a challenge we have where the request services need to be set up as basically the first thing in the pipeline or multitenant support doesn't work - if request services (the request lifetime) identifies the tenant _wrong_, you're hosed, which is what I think you're seeing. However, I don't know what happens when headers are resolved in the `HttpContext`. Super long story already too long, I'm curious if simply accessing the headers has a side effect of identifying the tenant [incorrectly] and then you're stuck with the wrong tenant for request services. A race condition, as it were.

Easy enough to check - our example uses query string and we know that works. Can you switch your example temporarily to be query string and see what happens?

- If it starts working, we know it may be a race condition.
- If it doesn't start working...
  - Try out our example, see if that works for you. It should; if it doesn't, there's something else going on.
  - Try copying our example verbatim and then changing only the query string identification to headers. If that stops working, we confirm the race condition; if it continues working, we know there's something up in your example that differs somehow from ours.

If it turns out to be a race condition, I'm not sure what to do about that. We're already setting request services as early as possible. I guess... well, let's just hope that's not it.

**Comment by jontycg** [comment]
Thanks for that feedback @tillig, I'll make sure I try that out and report back to you once I have some findings.

**Comment by tillig** [comment]
I verified that if we switch the `QueryStringTenantIdentificationStrategy` to be a `HeaderTenantIdentificationStrategy`...

```c#
// Instead of this...
if (context.Request.Query.TryGetValue("tenant", out StringValues tenantValues))
{
  //...
}

// Do this...
if (context.Request.Headers.TryGetValue("tenant", out StringValues tenantValues))
{
  //...
}
```

...that the sandbox app still works. That rules out any weirdness around race conditions. I have not yet tried out the provided repro app.

**Comment by tillig** [comment]
The problem in the repro is **incorrect object types and equality**.

For reference, here's the tenant ID strategy from the repro:

```c#
public class HeaderTenantIdentificationStrategy : ITenantIdentificationStrategy
{
  public HeaderTenantIdentificationStrategy(IHttpContextAccessor accessor)
  {
    Accessor = accessor;
  }
        
  public IHttpContextAccessor Accessor { get; private set; }
  public bool TryIdentifyTenant(out object tenantId)
  {
    tenantId = null;

    var httpContext = Accessor.HttpContext;
    if (httpContext != null)
    {
      tenantId = httpContext.Request.Headers["tenant"];
    }

    return tenantId != null;
  }
}
```

And, also for reference, the demo tenant ID strategy from the sandbox app:

```c#
public class QueryStringTenantIdentificationStrategy : ITenantIdentificationStrategy
{
  private readonly ILogger<QueryStringTenantIdentificationStrategy> _logger;

  public QueryStringTenantIdentificationStrategy(IHttpContextAccessor accessor, ILogger<QueryStringTenantIdentificationStrategy> logger)
  {
    Accessor = accessor;
    _logger = logger;
  }

  public IHttpContextAccessor Accessor { get; private set; }

  public bool TryIdentifyTenant(out object tenantId)
  {
    var context = Accessor.HttpContext;
    if (context == null)
    {
      // No current HttpContext. This happens during app startup
      // and isn't really an error, but is something to be aware of.
      tenantId = null;
      return false;
    }

    // Caching the value both speeds up tenant identification for
    // later and ensures we only see one log message indicating
    // relative success or failure for tenant ID.
    if (context.Items.TryGetValue("_tenantId", out tenantId))
    {
      // We've already identified the tenant at some point
      // so just return the cached value (even if the cached value
      // indicates we couldn't identify the tenant for this context).
      return tenantId != null;
    }

    if (context.Request.Query.TryGetValue("tenant", out StringValues tenantValues))
    {
      tenantId = tenantValues[0];
      context.Items["_tenantId"] = tenantId;
      _logger.LogInformation("Identified tenant: {tenant}", tenantId);
      return true;
    }

    _logger.LogWarning("Unable to identify tenant from query string. Falling back to default.");
    tenantId = null;
    context.Items["_tenantId"] = null;
    return false;
  }
}

```

There are a couple of issues that will cause this to fail.

## Problem 1: No null context handling

During app startup things are going to get resolved as part of singleton middleware and other framework functions. In the repro, it's missing the case we have in the demo tenant ID strategy:

```c#
if (context == null)
{
 // ...
}
```

**Null `HttpContext` must be handled.** The current repro strategy will throw unhandled `NullReferenceExceptions` without that. Putting a debugger on the `TryIdentifyTenant` method _does show_ it's getting hit at app startup. That's not what's causing the problem being reported, but it'll be a problem later.

## Problem 2: Object equality

The way tenant IDs are handled, they're `object` and the tenant ID is used [as a lifetime scope tag](https://github.com/autofac/Autofac.Multitenant/blob/5d2523373bf980b496e42c5bff719b0ccaa59ecd/src/Autofac.Multitenant/MultitenantContainer.cs#L365). Since it's `object`, there's no magic compiler auto-casting or anything - comparison all boils down to `object.Equals`. If the two objects are the same type (e.g., both strings) it'll use appropriate comparison (e.g., string equality).

**The repro tenant ID strategy isn't using strings.** The `HttpContext.Request.Headers["string"]` indexer returns an object of type `StringValues` - because you can have multiple values for a given header. That's also how `HttpContext.Request.QueryString` works.

So how come the sandbox app works and the repro doesn't?

In the repro, the `tenantId` is set _as the `StringValues`.

```c#
tenantId = httpContext.Request.Headers["tenant"];
```

In the sandbox demo, the `tenantId` is _the first item from the `StringValues`_.

```c#
    if (context.Request.Query.TryGetValue("tenant", out StringValues tenantValues))
    {
      tenantId = tenantValues[0];
      // ...
    }
```

Thus, in the sandbox demo app, the tenant ID is a `string`, and when that `string` is compared to the tenant ID lifetime scopes that are registered, it's `string.Equals`. In the repro app, it's `object.Equals` because it's trying to compare a `StringValues` object to a `string`.

**Change the repro to store a `string` instead of `StringValues` and it works.** I verified that locally on my clone of the repro.

I'd also _strongly_ recommend using `TryGetValues` instead of assuming the header will always be there. You'll get exceptions on missing headers as it's currently written.
