### ISSUE TITLE
.NET 6 update

### ISSUE THREAD

**Issue by alsami** [autofac/Autofac.AspNetCore.Multitenant#41]
* Target .NET 6
* Update CI / CD pipeline
* Maybe drop older frameworks? 2.1 is EOL

**Comment by tillig** [comment]
Looking at the current project, we support `netstandard2.0`, `netcoreapp3.1`, `net5.0`. I think those are still valid. .NET Core 2.1 [ended support August 21, 2021](https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/), but ASP.NET Core 2.1 on .NET Framework follows [the ASP.NET support policy](https://dotnet.microsoft.com/platform/support/policy/aspnet) where it's classified as a "tool." From what I gather, you get 12 months' notice for tools and they haven't given that notice yet. At least, nowhere I can find. I think we should probably keep supporting `netstandard2.0` as long as ASP.NET Core 2.1 is still alive _and_ as long as we keep it in core Autofac, whichever is _shorter_.

(That is, if we drop it from core Autofac before ASP.NET Core 2.1 is EOL, then it's probably fine to drop it here, too.)

Otherwise, yeah, a .NET 6 upgrade seems reasonable. :tada:

**Comment by alsami** [comment]
Sounds good to me. I'll make sure to keep all existing targets and just add the new one as well.
