### ISSUE TITLE
Problem combining CoreWCF and Autofac.Multitenant

### ISSUE THREAD

**Issue by Datorsmurf** [autofac/Autofac.AspNetCore.Multitenant#47]
## The problem
This is not really a bug in CoreWCF or Autofac.Multitenant but a problem that arises when trying to combine them. A short discussion of the problem and a suggested solution for it found here in the CoreWcf project. https://github.com/CoreWCF/CoreWCF/issues/1043

When trying to use the Mulitenancy in combination with CoreWCF-framework the CoreWcf-framwork resolves the services from the root scope even though the ITenantIdentificationStrategy has identified that call is for a tenant.

## Expected Behavior
The service resolved by the CureWcf is using the tentant scoped Lifetimescope

## Dependency Versions
Autofac.AspNetCore.Multitenant: 6.0.0
CoreWCF.Http: 1.3.2

**Comment by tillig** [comment]
I'm not really sure what to do about this, and I know that since WCF has a lot of different ways to control lifetime scope likely we won't be able to do much. [We have a whole separate integration package for classic WCF](https://github.com/autofac/Autofac.Multitenant.Wcf) that may provide some ideas on how best to hook in.

Unfortunately, I can't say we'll allocate any time to digging in and trying to research this. We're already stretched pretty thin trying to maintain the other integrations; if you have a specific proposal or PR we'd be happy to check it out or discuss. However, based on the discussion already in that other issue you linked, it sounds like that team, too, has indicated that the lifetime scopes will not always be matched based on HTTP request for the reasons I described. Likely what you need is some sort of CoreWCF-compatible port of the Autofac.Wcf and Autofac.Multitenant.Wcf packages... and that's not really on our radar at the moment.
